#!/bin/sh

set -e

openssl="../util/shlib_wrap.sh ../apps/openssl"

####################################################################

echo "Test PEM reader on various data formats"

test_cert_pass() {
    name=$1;
    $openssl x509 -text -noout -inform PEM -in pem/"$name" | \
        grep -q 'The Great State of Long-Winded Certificate Field Names Whereby to Increase the Output Size' || exit 1
    return 0
}

test_cert_fail() {
    name=$1;
    $openssl x509 -text -noout -inform PEM -in pem/"$name" | \
        grep -q 'The Great State of Long-Winded Certificate Field Names Whereby to Increase the Output Size' && exit 1
    return 0
}

test_dsa_pass() {
    name=$1
    $openssl pkey -inform PEM -passin file:pem/wellknown -noout -text -in "pem/$name" | \
        grep -q '68:42:02:16:63:54:16:eb:06:5c:ab:06:72:3b:78:' || exit 1
    return 0
}

test_dsa_fail() {
    name=$1
    $openssl pkey -inform PEM -passin file:pem/wellknown -noout -text -in "pem/$name" | \
        grep -q '68:42:02:16:63:54:16:eb:06:5c:ab:06:72:3b:78:' && exit 1
    return 0
}

for cert in cert cert-1023line cert-1024line cert-1025line cert-255line cert-256line cert-257line cert-infixwhitespace cert-longline cert-onecolumn cert-oneline cert-shortandlongline cert-shortline cert-threecolumn cert-trailingwhitespace; do
    test_cert_pass "${cert}.pem"
done

for cert in cert-blankline cert-comment cert-earlypad cert-extrapad cert-junk cert-misalignedpad; do
    test_cert_fail "${cert}.pem"
done

for dsa in dsa dsa-1023line dsa-1024line dsa-1025line dsa-255line dsa-256line dsa-257line dsa-infixwhitespace dsa-leadingwhitespace dsa-longline dsa-onecolumn dsa-oneline dsa-shortandlongline dsa-shortline dsa-threecolumn dsa-trailingwhitespace; do
    test_dsa_pass "${dsa}.pem"
done

for dsa in dsa-blankline dsa-comment dsa-corruptedheader dsa-corruptiv dsa-earlypad dsa-extrapad dsa-junk dsa-misalignedpad dsa-onelineheader; do
    test_dsa_fail "${dsa}.pem"
done

$openssl pkey -inform PEM -noout -text -in pem/beermug.pem | grep -q '00:a0:3a:21:14:5d:cd:b6:d5:a0:3e:49:23:c1:3a:' || exit 1

# All good!
exit 0
