#!/bin/sh

clientcache2test="../util/shlib_wrap.sh ./clientcache2test"

#############################################################################

echo Test Client Cache \(2\)
if [ ! -d gen ]; then
    ./gen_cert.sh server
fi

# test client session reuse, expected to work on all protocols except sslv23
$clientcache2test         || exit 1
$clientcache2test --sslv2 || exit 1
$clientcache2test --sslv3 || exit 1
$clientcache2test --tlsv1 || exit 1

exit 0
