#!/bin/sh

ciphpreftest="./ciphpreftest"

#############################################################################

echo Test server cipher pref
if [ ! -d gen ]; then
    ./gen_cert.sh server
fi

# test effectiveness of server cipher preferences
$ciphpreftest           || exit 1
$ciphpreftest --tls     || exit 1
$ciphpreftest --sslv3   || exit 1
$ciphpreftest --tlsv1   || exit 1
$ciphpreftest --tlsv1_1 || exit 1
$ciphpreftest --tlsv1_2 || exit 1

exit 0
