=pod

=head1 NAME

SSL_CTX_set_ciphers_ex - choose list of available SSL_CIPHERs

=head1 SYNOPSIS

 #include <openssl/ssl.h>

 int SSL_CTX_set_ciphers_ex(SSL_CTX *ctx, const char *str, unsigned long flags);
 int SSL_CTX_set_preferred_ciphers(SSL_CTX *ctx, const char *str);

=head1 DESCRIPTION

SSL_CTX_set_ciphers_ex() sets the list of available ciphers for B<ctx>
using the control string B<str> and additionally setting the SSL options in 
flags (as in SSL_CTX_set_options). SSL_CTX_set_preferred_ciphers is a defined
call that sets the ciphers and the option SSL_OP_CIPHER_SERVER_PREFERENCE.

The format of the string is described
in L<ciphers(1)|ciphers(1)>. The list of ciphers is inherited by all
B<ssl> objects created from B<ctx>.

=head1 NOTES

Using SSL_CTX_set_preferred_ciphers() in a server context will make sure that 
during negotiation ciphers are chosen from the given list in the order they appear
until the server finds one that is also supported by the client. Client 
preferences or cipher orders are ignored.

=head1 RETURN VALUES

SSL_CTX_set_ciphers_ex() and SSL_set_preferred_ciphers() return 1 if any cipher
could be selected and 0 on complete failure.

=head1 SEE ALSO

L<ssl(3)|ssl(3)>, L<SSL_get_ciphers(3)|SSL_get_ciphers(3)>,
L<SSL_CTX_set_options(3)|SSL_CTX_set_options(3)>,
L<SSL_CTX_set_cipher_list(3)|SSL_CTX_set_cipher_list(3)>,
L<SSL_CTX_use_certificate(3)|SSL_CTX_use_certificate(3)>,
L<SSL_CTX_set_tmp_rsa_callback(3)|SSL_CTX_set_tmp_rsa_callback(3)>,
L<SSL_CTX_set_tmp_dh_callback(3)|SSL_CTX_set_tmp_dh_callback(3)>,
L<ciphers(1)|ciphers(1)>

=cut
